name: Node.js CI & Deploy

on:
  push:
<<<<<<< HEAD
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
=======
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
>>>>>>> e1f8e388f63c975ecb6f55f0d29369e6d8e6c53c

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
